
#ifndef C_CACODEGENTEST_CODE_GEN_H
#define C_CACODEGENTEST_CODE_GEN_H
// This file is generated by the code generator. Do not modify this file manually.


#include <CAMeta/CAMetaCodeGenCommon.h>

#ifdef __cplusplus
extern "C"
{
#endif
    CAINTERFACE void* New_InnerStruct();
    CAINTERFACE void* New_InnerStruct_Copy(const void* srcPtr);
    CAINTERFACE void Release_InnerStruct(void* objPtr);
    CAINTERFACE void* New_TestProp();
    CAINTERFACE void* New_TestProp_Int_Int(int xx, int yy);
    CAINTERFACE void* New_TestProp_Copy(const void* srcPtr);
    CAINTERFACE void Release_TestProp(void* objPtr);
    CAINTERFACE void TestProp_TestFunction(void* thisPtr, int a, float* b, int* c, int d, int* e, void* f, void* g, void* h);
    CAINTERFACE void* TestProp_Clone(void* thisPtr);
    CAINTERFACE void* TestProp_Inner(void* thisPtr);
    CAINTERFACE void* TestProp_GenTestClass1(void* thisPtr);
    CAINTERFACE void* New_TestClass1();
    CAINTERFACE void* New_TestClass1_Copy(const void* srcPtr);
    CAINTERFACE void Release_TestClass1(void* objPtr);
#ifdef __cplusplus
}
#endif
#endif // C_CACODEGENTEST_CODE_GEN_H
