
// This file is generated by the code generator. Do not modify this file manually.
#include <TestHeader.h>
#include "C_CACodeGenTest_CodeGen.h"

#ifdef __cplusplus
extern "C"
{
#endif
    
            CAINTERFACE void* New_InnerStruct()
            {
                return new TestNameSpaceB::TestProp::InnerStruct();
            }
        
    
            CAINTERFACE void* New_InnerStruct_Copy(const void* srcPtr)
            {
                return new TestNameSpaceB::TestProp::InnerStruct(*(const TestNameSpaceB::TestProp::InnerStruct*)srcPtr);
            }
        
    
        CAINTERFACE void Release_InnerStruct(void* objPtr)
        {
            delete (TestNameSpaceB::TestProp::InnerStruct*)objPtr;
        }
    
    
            CAINTERFACE void* New_TestProp()
            {
                return new TestNameSpaceB::TestProp();
            }
        
    
            CAINTERFACE void* New_TestProp_Int_Int(int xx, int yy)
            {
                return new TestNameSpaceB::TestProp(xx, yy);
            }
            
    
            CAINTERFACE void* New_TestProp_Copy(const void* srcPtr)
            {
                return new TestNameSpaceB::TestProp(*(const TestNameSpaceB::TestProp*)srcPtr);
            }
        
    
        CAINTERFACE void Release_TestProp(void* objPtr)
        {
            delete (TestNameSpaceB::TestProp*)objPtr;
        }
    
    
    CAINTERFACE void TestProp_TestFunction(void* thisPtr, int a, float* b, int* c, int d, int* e, void* f, void* g, void* h)
    {
        
    ((TestNameSpaceB::TestProp*)thisPtr)->TestFunction(a, *b, c, d, *e, *(const TestNameSpaceB::TestClass1*)f, *(TestNameSpaceB::TestClass1*)g, (TestNameSpaceB::TestClass1*)h);
    
     
    }
    
    
    CAINTERFACE void* TestProp_Clone(void* thisPtr)
    {
        
    auto returnVal = ((TestNameSpaceB::TestProp*)thisPtr)->Clone();
    return New_TestProp_Copy(&returnVal);
     
    }
    
    
    CAINTERFACE void* TestProp_Inner(void* thisPtr)
    {
        
    auto returnVal = ((TestNameSpaceB::TestProp*)thisPtr)->Inner();
    return New_InnerStruct_Copy(&returnVal);
     
    }
    
    
    CAINTERFACE void* TestProp_GenTestClass1(void* thisPtr)
    {
        
    auto returnVal = ((TestNameSpaceB::TestProp*)thisPtr)->GenTestClass1();
    return New_TestClass1_Copy(&returnVal);
     
    }
    
    
            CAINTERFACE void* New_TestClass1()
            {
                return new TestNameSpaceB::TestClass1();
            }
        
    
            CAINTERFACE void* New_TestClass1_Copy(const void* srcPtr)
            {
                return new TestNameSpaceB::TestClass1(*(const TestNameSpaceB::TestClass1*)srcPtr);
            }
        
    
        CAINTERFACE void Release_TestClass1(void* objPtr)
        {
            delete (TestNameSpaceB::TestClass1*)objPtr;
        }
    
#ifdef __cplusplus
}
#endif
