
// This file is generated by the code generator. Do not modify this file manually.
using System;
using System.Runtime.InteropServices;

public class TestProp
{
    //Handle to the native object
    public IntPtr handle;
}